### ISSUE TITLE
`.forRoot()` not working

### ISSUE THREAD

**Issue by loqtor** [DethAriel/ng2-recaptcha#6] opened 2016-12-05 20:41 UTC
Hi,

The `forRoot()` method does not seem to work for me. 

Here's my package.json:

```json
{
  "name": "my-project",
  "version": "1.0.0",
  "description": "My Project",
  "author": "Alphero",
  "contributors": [
    "Martín Martínez"
  ],
  "license": "UNLICENSED",
  "engines": {
    "node": ">=5.11.0",
    "npm": ">=3.8.6"
  },
  "scripts": {
    "reinstall": "rimraf node_modules && npm cache clean && npm install",
    "postinstall": "npm run typings",
    "typings": "typings install",
    "updatetypings": "typings ls | awk '$2 ~ /.+/ {print $2}' | xargs -I {} typings i dt~{} -SG",
    "prebuild": "rimraf dist",
    "build": "webpack --config config/webpack.prod.js --progress --profile --bail",
    "start": "webpack-dev-server --inline --progress --port 8079 --debug",
    "test": "karma start"
  },
  "keywords": [],
  "dependencies": {
    "@angular/common": "^2.0.1",
    "@angular/compiler": "^2.0.1",
    "@angular/core": "^2.0.1",
    "@angular/forms": "^2.0.1",
    "@angular/http": "^2.0.1",
    "@angular/platform-browser": "^2.0.1",
    "@angular/platform-browser-dynamic": "^2.0.1",
    "@angular/router": "^3.0.1",
    "angular2-recaptcha": "^0.3.4",
    "angular2-text-mask": "^2.1.0",
    "core-js": "^2.4.1",
    "headroom.js": "^0.9.3",
    "moment": "^2.17.0",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "^0.6.23"
  },
  "devDependencies": {
    "autoprefixer": "^6.4.1",
    "browser-sync": "^2.16.0",
    "browser-sync-webpack-plugin": "^1.1.3",
    "css-loader": "^0.25.0",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.9.0",
    "html-loader": "^0.4.4",
    "html-webpack-plugin": "^2.22.0",
    "jasmine-core": "^2.5.2",
    "karma": "^1.3.0",
    "karma-jasmine": "^1.0.2",
    "karma-phantomjs-launcher": "^1.0.2",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-spec-reporter": "0.0.26",
    "node-sass": "^3.10.0",
    "null-loader": "^0.1.1",
    "phantomjs-prebuilt": "^2.1.12",
    "postcss-loader": "^0.13.0",
    "raw-loader": "^0.5.1",
    "rimraf": "^2.5.4",
    "sass-loader": "^4.0.2",
    "style-loader": "^0.13.1",
    "ts-loader": "^0.8.1",
    "tslint": "^3.15.1",
    "typescript": "^2.1.0-dev.20160926",
    "typings": "^1.4.0",
    "webpack": "^1.13.2",
    "webpack-dev-server": "^1.16.1",
    "webpack-merge": "^0.14.1"
  }
}
```

I get the `forRoot() is not a function` error when going: 
```javascript
import { RecaptchaModule } from 'ng2-recaptcha';
import { BrowserModule }  from '@angular/platform-browser';

@NgModule({
  bootstrap: [MyApp],
  declarations: [MyApp],
  imports: [
    BrowserModule,
    RecaptchaModule.forRoot(), // Keep in mind the "forRoot"-magic nuances!
  ],
})
export class MyAppModule { }
```

Let me know if you need further information.

Cheers!
Martín.

**Comment by DethAriel** [comment] 2016-12-05 20:56
To start with, I don't see the `ng2-recaptcha` module referenced in your `package.json`, just the `angular2-recaptcha` (which is a different library). Could you please double-check that you're posting issues to the correct repo / using the right module?

**Comment by loqtor** [comment] 2016-12-05 20:59
Hi, 

Sorry about that. I moved to a different `recaptcha` implementation after this did not do it for me.
The rest of the setup is what I had when I tried yours.

Cheers!
Martín.

**Comment by DethAriel** [comment] 2016-12-05 21:02
Do you mind also posting your `tsconfig.json` contents? I cannot reproduce the issue you're seeing so far, maybe that will help

**Comment by loqtor** [comment] 2016-12-05 21:03
Thanks for the quick reply, man.

Here's my `tsconfig.json`:

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": true,
    "noImplicitAny": false,
    "baseUrl": ".",
    "paths": {
      "*": [
        "app/components/*",
        "app/*"
      ]
    }
  },
  "exclude": [
    "node_modules",
    "dist",
    "typings/index.d.ts",
    "app/assets",
    "app/styles"
  ]
}
```

I hope that helps. :)

Cheers!
Martín.

**Comment by DethAriel** [comment] 2016-12-05 21:26
@loqtor sorry, but still no progress on that. Instead of me asking you to post a gazillion files here, here's what you can do. The [`gh-pages` branch](https://github.com/DethAriel/ng2-recaptcha/tree/gh-pages/) has the source code for [demo site](https://dethariel.github.io/ng2-recaptcha/basic). The files you might be interested in are [/examples/app/main-basic.ts](https://github.com/DethAriel/ng2-recaptcha/blob/gh-pages/examples/app/main-basic.ts) and pretty much the rest of [/examples/](https://github.com/DethAriel/ng2-recaptcha/blob/gh-pages/examples/) directory :)
If you could also create a plunker that shows the issue, that would be awesome! You can use [this](https://plnkr.co/edit/aoO1S8Awq4jl7MRWiez7) as a starting point.

I'm sorry to hear that this didn't work for you.

**Comment by loqtor** [comment] 2016-12-05 21:31
No worries, man. 

It must be something on my side. I was more about letting you know that the instructions were a bit misleading, since it seemed a real shame given that you did a really good job on this module. :)

Once again, thanks for your help.

Cheers!
Martín.

**Comment by DethAriel** [comment] 2016-12-05 21:33
Thx, @loqtor !

I'm going to leave this one open for now - if anyone else encounters this issue, please submit a comment

**Comment by DethAriel** [comment] 2016-12-27 23:16
Closing this issue since no more complaints have been heard

**Closed by DethAriel** 2016-12-27 23:16 UTC
Labels: help wanted, need info/repro
